project:
  type: website
  output-dir: docs
website:
  title: Posterior Predictive Checks
  twitter-card:
    image: "docs/case_studies/ordinal/ordinal_files/figure-html/reliability-diagrams_1-1.svg"
  navbar:
    right:
      - text: Home
        href: index.html
      - icon: github
        href: https://github.com/TeemuSailynoja/ppc-casestudies
format:
  html:
    theme:
      light:
      - flatly
      - styles/light.scss
      dark:
      - darkly
      - styles/dark.scss
    css: styles/styles.css
freeze: auto
