project:
  type: website
  output-dir: docs
website:
  title: Posterior Predictive Checks
  navbar:
    right:
    - icon: github
      href: https://github.com/TeemuSailynoja/ppc-casestudies
format:
  html:
    theme:
      light:
      - flatly
      - light.scss
      dark:
      - darkly
      - dark.scss
    css: styles.css
freeze: auto
